Added/Revised T1 Entry EWAR Frigates
Minmatar-Fleet-Alliance/FL33T-Fits pull request #85
Opened 2024-02-06 15:32 UTC by Epicloa-Program

Added detailed descriptions with all the relevant information for each ship. Gives newer players all the information they need to fly the ship effectively.

2024-02-07 13:19 UTC, bearthatcares commented on Fits/Frigates/[ADV-5] Malediction.md
This shouldn't be apart of this PR

2024-02-07 13:19 UTC, bearthatcares commented on Fits/Interceptors/[ADV-5] Ares.md
Separate branch!!!!

2024-02-07 13:20 UTC, bearthatcares requested changes
We already have fittings for all these, example https://tools.minmatar.org/fleets/fittings/nvy-30-vigil/

How do these differ and were we aware of those?

2024-02-07 13:45 UTC, Epicloa-Program commented on Fits/Frigates/[ADV-5] Malediction.md
Sorry I thought I did these as a separate thing, I just needed the file structure from the previous PR so I thought I clicked the right thing.

2024-02-07 13:49 UTC, Epicloa-Program commented
> We already have fittings for all these, example https://tools.minmatar.org/fleets/fittings/nvy-30-vigil/
> 
> How do these differ and were we aware of those?

Yeah so the primary differences that I aimed for were:

A) Lowered price, the new ones are roughly half the price of the old (albeit cheap to cheaper but they didn't really lose anything in the process).
B) Cap stability and maximum effectiveness with low SP (used max alpha skills as default for these). Example being the current Vigil fit is 2.9mil and not stable even with all 5s, cap lasts a whopping 60s with max alpha skills. New Vigil is 1.16mil, cap stable with max alpha skills, and has lock-range to actually be at 100km. A consistent issue with the current fits is that they have no caplife and no lock range, especially with lower SP.

2024-02-20 16:19 UTC, bearthatcares approved these changes

2024-02-21 22:13 UTC, closed without merging

2024-02-21 22:13 UTC, Epicloa-Program commented
Fixing PRs to avoid conflicts.